package com.example.catcoins;

import com.example.catcoins.model.BalanceHistory;
import com.example.catcoins.model.Client;
import com.example.catcoins.model.Transaction;
import com.example.catcoins.model.User;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.TableCell;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;

public class BalanceHistoryController extends MenuLoader {

    @FXML
    private Text userNameText;
    @FXML
    private Text userEmailText;
    @FXML
    private Text userRoleText;
    @FXML
    private Text userStatusText;
    @FXML
    private Text balanceText;
    @FXML
    private Text coinBalanceText;
    @FXML
    private TableView<BalanceHistory> BalanceHistoryTable;
    @FXML
    private TableColumn<Transaction, Date> DateColumn;
    @FXML
    private TableColumn<Transaction, Double> BalanceColumn;
    @FXML
    private TableColumn<Transaction, Double> PendingBalanceColumn;
    @FXML
    private VBox Stack;
    @FXML
    private BorderPane MainPanel;
    @FXML
    private StackPane Background;

    private final ObservableList<BalanceHistory> BalanceHistoryList = FXCollections.observableArrayList();

    @Override
    public void setLoggedUser(User user) {
        super.setLoggedUser(user);
        super.LoadMenus(Stack, MainPanel);
        loadHistory();
    }


    private void loadHistory() {
        BalanceColumn.setCellValueFactory(new PropertyValueFactory<>("Balance"));
        PendingBalanceColumn.setCellValueFactory(new PropertyValueFactory<>("PendingBalance"));
        DateColumn.setCellValueFactory(new PropertyValueFactory<>("Date"));
        String sql = " SELECT * FROM BalanceHistory where Wallet = ? ORDER BY Date DESC";
        try (Connection conn = DatabaseConnection.getInstance().getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            Client LoggedClient = (Client) super.getLoggedUser();
            stmt.setInt(1,   LoggedClient.getWallet().getID());
            ResultSet rs = stmt.executeQuery();

            BalanceHistoryList.clear();
            while (rs.next()) {
                BalanceHistory b = new BalanceHistory(
                        rs.getTimestamp("Date").toString(),
                        rs.getDouble("PendingBalance"),
                        rs.getDouble("Balance")
                );
                BalanceHistoryList.add(b);
            }

            BalanceHistoryTable.setItems(BalanceHistoryList);
            System.out.println("Loaded " + BalanceHistoryList.size() + " transactions for user ID: " + LoggedClient.getWallet().getID());

        } catch (SQLException e) {
            System.err.println("Error loading transactions: " + e.getMessage());
            handleDatabaseError(e);
            BalanceHistoryTable.setItems(FXCollections.emptyObservableList());
        }
    }

    private void handleDatabaseError(SQLException e) {
        e.printStackTrace();
        System.err.println("Database error: " + e.getMessage());
    }

    @FXML
    private void exportLineChartToCSV() throws IOException {
        // Garante que o diretório existe
        java.nio.file.Path dirPath = Paths.get("src/main/resources/CSV");
        if (!Files.exists(dirPath)) {
            Files.createDirectories(dirPath);
        }

        // Cria o arquivo CSV com separador ponto e vírgula
        try (FileWriter writer = new FileWriter("src/main/resources/CSV/balanceHistory.csv")) {
            writer.write("Date;Balance;PendingBalance\n");
            for (BalanceHistory bh : BalanceHistoryTable.getItems()) {
                String line = String.format(Locale.US, "%s;%.2f;%.2f\n",
                        bh.getDate().toString(),
                        bh.getBalance(),
                        bh.getPendingBalance()
                );
                writer.write(line);
            }
        }

        String subject = "CatCoins Balance History";
        String content = "This email was automatically generated by the CatCoins system.";

        // Envia o e-mail com texto simples e anexo
        EmailConfig.SendEmailAttach(super.getLoggedUser().getEmail(), content, subject, "src/main/resources/CSV/balanceHistory.csv");

        // Limpa o arquivo temporário
        java.nio.file.Path path = Paths.get("src/main/resources/CSV/balanceHistory.csv");
        try {
            Files.delete(path);
        } catch (IOException e) {
            System.out.println("Error removing file: " + e.getMessage());
        }

    // Substituindo o Alert padrão pelo ShowAlert personalizado
        AlertUtils.showAlert(Background, Alert.AlertType.ERROR, "Export completed", "The full history has been sent to your email!");
    }
}